//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3634
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ManicDigger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ManicDigger.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot write to chat log file {0}..
        /// </summary>
        public static string CannotWriteChatLog {
            get {
                return ResourceManager.GetString("CannotWriteChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chunk updates: {0}.
        /// </summary>
        public static string ChunkUpdates {
            get {
                return ResourceManager.GetString("ChunkUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Connecting {
            get {
                return ResourceManager.GetString("Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} KB.
        /// </summary>
        public static string ConnectingProgressKilobytes {
            get {
                return ResourceManager.GetString("ConnectingProgressKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}%.
        /// </summary>
        public static string ConnectingProgressPercent {
            get {
                return ResourceManager.GetString("ConnectingProgressPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default keys.
        /// </summary>
        public static string DefaultKeys {
            get {
                return ResourceManager.GetString("DefaultKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fog distance: {0}.
        /// </summary>
        public static string FogDistance {
            get {
                return ResourceManager.GetString("FogDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font: {0}.
        /// </summary>
        public static string FontOption {
            get {
                return ResourceManager.GetString("FontOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame rate: lag simulation..
        /// </summary>
        public static string FrameRateLagSimulation {
            get {
                return ResourceManager.GetString("FrameRateLagSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame rate: unlimited..
        /// </summary>
        public static string FrameRateUnlimited {
            get {
                return ResourceManager.GetString("FrameRateUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frame rate: vsync..
        /// </summary>
        public static string FrameRateVsync {
            get {
                return ResourceManager.GetString("FrameRateVsync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freemove is not allowed on this server..
        /// </summary>
        public static string FreemoveNotAllowed {
            get {
                return ResourceManager.GetString("FreemoveNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manic Digger.
        /// </summary>
        public static string GameName {
            get {
                return ResourceManager.GetString("GameName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string Graphics {
            get {
                return ResourceManager.GetString("Graphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid game version. Local: {0}, Server: {1}. Do you want to connect anyway?.
        /// </summary>
        public static string InvalidVersionConnectAnyway {
            get {
                return ResourceManager.GetString("InvalidVersionConnectAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: {1}.
        /// </summary>
        public static string KeyChange {
            get {
                return ResourceManager.GetString("KeyChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string KeyChat {
            get {
                return ResourceManager.GetString("KeyChat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team Chat.
        /// </summary>
        public static string KeyTeamChat {
            get {
                return ResourceManager.GetString("KeyTeamChat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string KeyBlockInfo {
            get {
                return ResourceManager.GetString("KeyBlockInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        public static string KeyUse {
            get {
                return ResourceManager.GetString("KeyUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free move.
        /// </summary>
        public static string KeyFreeMove {
            get {
                return ResourceManager.GetString("KeyFreeMove", resourceCulture);
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string KeyTextEditor {
            get {
                return ResourceManager.GetString("KeyTexteditor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string KeyFullscreen {
            get {
                return ResourceManager.GetString("KeyFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump.
        /// </summary>
        public static string KeyJump {
            get {
                return ResourceManager.GetString("KeyJump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move back.
        /// </summary>
        public static string KeyMoveBack {
            get {
                return ResourceManager.GetString("KeyMoveBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move foward.
        /// </summary>
        public static string KeyMoveFoward {
            get {
                return ResourceManager.GetString("KeyMoveFoward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move left.
        /// </summary>
        public static string KeyMoveLeft {
            get {
                return ResourceManager.GetString("KeyMoveLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move right.
        /// </summary>
        public static string KeyMoveRight {
            get {
                return ResourceManager.GetString("KeyMoveRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}x move speed.
        /// </summary>
        public static string KeyMoveSpeed {
            get {
                return ResourceManager.GetString("KeyMoveSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players list.
        /// </summary>
        public static string KeyPlayersList {
            get {
                return ResourceManager.GetString("KeyPlayersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn.
        /// </summary>
        public static string KeyRespawn {
            get {
                return ResourceManager.GetString("KeyRespawn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Respawn.
        /// </summary>
        public static string KeyReloadWeapon {
            get {
                return ResourceManager.GetString("KeyReloadWeapon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reverse minecart.
        /// </summary>
        public static string KeyCraft {
            get {
                return ResourceManager.GetString("KeyCraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverse minecart.
        /// </summary>
        public static string KeyReverseMinecart {
            get {
                return ResourceManager.GetString("KeyReverseMinecart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys.
        /// </summary>
        public static string Keys {
            get {
                return ResourceManager.GetString("Keys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string KeyScreenshot {
            get {
                return ResourceManager.GetString("KeyScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spawn position.
        /// </summary>
        public static string KeySetSpawnPosition {
            get {
                return ResourceManager.GetString("KeySetSpawnPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show material selector.
        /// </summary>
        public static string KeyShowMaterialSelector {
            get {
                return ResourceManager.GetString("KeyShowMaterialSelector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-person camera.
        /// </summary>
        public static string KeyThirdPersonCamera {
            get {
                return ResourceManager.GetString("KeyThirdPersonCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle fog distance.
        /// </summary>
        public static string KeyToggleFogDistance {
            get {
                return ResourceManager.GetString("KeyToggleFogDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move: Free..
        /// </summary>
        public static string MoveFree {
            get {
                return ResourceManager.GetString("MoveFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move: Free, Noclip..
        /// </summary>
        public static string MoveFreeNoclip {
            get {
                return ResourceManager.GetString("MoveFreeNoclip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move: Normal..
        /// </summary>
        public static string MoveNormal {
            get {
                return ResourceManager.GetString("MoveNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Speed: {0}..
        /// </summary>
        public static string MoveSpeed {
            get {
                return ResourceManager.GetString("MoveSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No materials for crafting..
        /// </summary>
        public static string NoMaterialsForCrafting {
            get {
                return ResourceManager.GetString("NoMaterialsForCrafting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (press {0} to use).
        /// </summary>
        public static string PressToUse {
            get {
                return ResourceManager.GetString("PressToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respawn..
        /// </summary>
        public static string Respawn {
            get {
                return ResourceManager.GetString("Respawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to game.
        /// </summary>
        public static string ReturnToGame {
            get {
                return ResourceManager.GetString("ReturnToGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to main menu.
        /// </summary>
        public static string ReturnToMainMenu {
            get {
                return ResourceManager.GetString("ReturnToMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to options menu.
        /// </summary>
        public static string ReturnToOptionsMenu {
            get {
                return ResourceManager.GetString("ReturnToOptionsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadows: {0}.
        /// </summary>
        public static string ShadowsOption {
            get {
                return ResourceManager.GetString("ShadowsOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound: {0}.
        /// </summary>
        public static string SoundOption {
            get {
                return ResourceManager.GetString("SoundOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn position set..
        /// </summary>
        public static string SpawnPositionSet {
            get {
                return ResourceManager.GetString("SpawnPositionSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spawn position set to: {0}.
        /// </summary>
        public static string SpawnPositionSetTo {
            get {
                return ResourceManager.GetString("SpawnPositionSetTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triangles: {0}.
        /// </summary>
        public static string Triangles {
            get {
                return ResourceManager.GetString("Triangles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use server textures (restart): {0}.
        /// </summary>
        public static string UseServerTexturesOption {
            get {
                return ResourceManager.GetString("UseServerTexturesOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View distance: {0}.
        /// </summary>
        public static string ViewDistanceOption {
            get {
                return ResourceManager.GetString("ViewDistanceOption", resourceCulture);
            }
        }
    }
}
